/**
 * @fileoverview BAP type exports
 * @module @browseragentprotocol/core/types
 */

// Protocol types (JSON-RPC 2.0)
export {
  // Version
  BAP_VERSION,
  // Schemas
  RequestIdSchema,
  JSONRPCErrorDataSchema,
  JSONRPCErrorSchema,
  JSONRPCRequestSchema,
  JSONRPCSuccessResponseSchema,
  JSONRPCErrorResponseSchema,
  JSONRPCNotificationSchema,
  JSONRPCResponseSchema,
  JSONRPCMessageSchema,
  // Types
  type RequestId,
  type JSONRPCError,
  type JSONRPCRequest,
  type JSONRPCSuccessResponse,
  type JSONRPCErrorResponse,
  type JSONRPCNotification,
  type JSONRPCResponse,
  type JSONRPCMessage,
  // Error codes
  ErrorCodes,
  type ErrorCode,
  // Type guards
  isRequest,
  isResponse,
  isNotification,
  isErrorResponse,
  // Helper functions
  createRequest,
  createSuccessResponse,
  createErrorResponse,
  createNotification,
} from "./protocol.js";

// Selector types
export {
  // ARIA roles
  AriaRoleSchema,
  type AriaRole,
  // Selector schemas
  CSSSelectorSchema,
  XPathSelectorSchema,
  RoleSelectorSchema,
  TextSelectorSchema,
  LabelSelectorSchema,
  PlaceholderSelectorSchema,
  TestIdSelectorSchema,
  SemanticSelectorSchema,
  CoordinatesSelectorSchema,
  RefSelectorSchema,
  BAPSelectorSchema,
  // Selector types
  type CSSSelector,
  type XPathSelector,
  type RoleSelector,
  type TextSelector,
  type LabelSelector,
  type PlaceholderSelector,
  type TestIdSelector,
  type SemanticSelector,
  type CoordinatesSelector,
  type RefSelector,
  type BAPSelector,
  // Factory functions
  css,
  xpath,
  role,
  text,
  label,
  placeholder,
  testId,
  semantic,
  coords,
  ref,
} from "./selectors.js";

// Common types
export {
  // Bounding box
  BoundingBoxSchema,
  type BoundingBox,
  // Modifiers and buttons
  KeyModifierSchema,
  MouseButtonSchema,
  type KeyModifier,
  type MouseButton,
  // Action options
  ActionOptionsSchema,
  ClickOptionsSchema,
  TypeOptionsSchema,
  ScrollDirectionSchema,
  ScrollAmountSchema,
  ScrollOptionsSchema,
  type ActionOptions,
  type ClickOptions,
  type TypeOptions,
  type ScrollDirection,
  type ScrollAmount,
  type ScrollOptions,
  // Screenshot options
  ScreenshotFormatSchema,
  ScreenshotScaleSchema,
  ScreenshotOptionsSchema,
  type ScreenshotFormat,
  type ScreenshotScale,
  type ScreenshotOptions,
  // Page types
  PageStatusSchema,
  WaitUntilStateSchema,
  ViewportSchema,
  PageSchema,
  type PageStatus,
  type WaitUntilState,
  type Viewport,
  type Page,
  // Storage types
  SameSiteAttributeSchema,
  CookieSchema,
  StorageItemSchema,
  OriginStorageSchema,
  StorageStateSchema,
  type SameSiteAttribute,
  type Cookie,
  type OriginStorage,
  type StorageState,
  // Accessibility types
  CheckedStateSchema,
  AccessibilityNodeSchema,
  type CheckedState,
  type AccessibilityNode,
  // Content types
  ContentFormatSchema,
  type ContentFormat,
  // Network types
  HttpMethodSchema,
  ResourceTypeSchema,
  type HttpMethod,
  type ResourceType,
} from "./common.js";

// Method parameter and result types
export {
  // Browser methods
  BrowserTypeSchema,
  ProxyConfigSchema,
  BrowserLaunchParamsSchema,
  BrowserLaunchResultSchema,
  BrowserCloseParamsSchema,
  type BrowserType,
  type ProxyConfig,
  type BrowserLaunchParams,
  type BrowserLaunchResult,
  type BrowserCloseParams,
  // Page methods
  GeolocationSchema,
  PageCreateParamsSchema,
  PageNavigateParamsSchema,
  PageNavigateResultSchema,
  PageReloadParamsSchema,
  PageGoBackParamsSchema,
  PageGoForwardParamsSchema,
  PageCloseParamsSchema,
  PageListResultSchema,
  PageActivateParamsSchema,
  type Geolocation,
  type PageCreateParams,
  type PageCreateParams as PageCreateOptions,
  type PageNavigateParams,
  type PageNavigateResult,
  type PageReloadParams,
  type PageGoBackParams,
  type PageGoForwardParams,
  type PageCloseParams,
  type PageListResult,
  type PageActivateParams,
  // Action methods
  PositionSchema,
  ActionClickParamsSchema,
  ActionDblclickParamsSchema,
  ActionTypeParamsSchema,
  ActionFillParamsSchema,
  ActionClearParamsSchema,
  ActionPressParamsSchema,
  ActionHoverParamsSchema,
  ActionScrollParamsSchema,
  ActionSelectParamsSchema,
  ActionCheckParamsSchema,
  ActionUncheckParamsSchema,
  FileUploadSchema,
  ActionUploadParamsSchema,
  ActionDragParamsSchema,
  type ActionClickParams,
  type ActionDblclickParams,
  type ActionTypeParams,
  type ActionFillParams,
  type ActionClearParams,
  type ActionPressParams,
  type ActionHoverParams,
  type ActionScrollParams,
  type ActionSelectParams,
  type ActionCheckParams,
  type ActionUncheckParams,
  type FileUpload,
  type ActionUploadParams,
  type ActionDragParams,
  // Observation methods
  ObserveScreenshotParamsSchema,
  ObserveScreenshotResultSchema,
  AccessibilityTreeOptionsSchema,
  ObserveAccessibilityParamsSchema,
  ObserveAccessibilityResultSchema,
  DOMSnapshotOptionsSchema,
  ObserveDOMParamsSchema,
  ObserveDOMResultSchema,
  ElementPropertySchema,
  ObserveElementParamsSchema,
  ObserveElementResultSchema,
  PaperFormatSchema,
  ObservePDFParamsSchema,
  ObservePDFResultSchema,
  ObserveContentParamsSchema,
  ObserveContentResultSchema,
  ObserveAriaSnapshotParamsSchema,
  ObserveAriaSnapshotResultSchema,
  type ObserveScreenshotParams,
  type ObserveScreenshotResult,
  type AccessibilityTreeOptions,
  type ObserveAccessibilityParams,
  type ObserveAccessibilityResult,
  type DOMSnapshotOptions,
  type ObserveDOMParams,
  type ObserveDOMResult,
  type ElementProperty,
  type ObserveElementParams,
  type ObserveElementResult,
  type PaperFormat,
  type ObservePDFParams,
  type ObservePDFResult,
  type ObserveContentParams,
  type ObserveContentResult,
  type ObserveAriaSnapshotParams,
  type ObserveAriaSnapshotResult,
  // Storage methods
  StorageGetStateParamsSchema,
  StorageSetStateParamsSchema,
  StorageGetCookiesParamsSchema,
  StorageGetCookiesResultSchema,
  StorageSetCookiesParamsSchema,
  StorageClearCookiesParamsSchema,
  type StorageGetStateParams,
  type StorageSetStateParams,
  type StorageGetCookiesParams,
  type StorageGetCookiesResult,
  type StorageSetCookiesParams,
  type StorageClearCookiesParams,
  // Network methods
  InterceptPatternSchema,
  InterceptHandlerSchema,
  NetworkInterceptParamsSchema,
  NetworkFulfillParamsSchema,
  AbortReasonSchema,
  NetworkAbortParamsSchema,
  NetworkContinueParamsSchema,
  type InterceptPattern,
  type InterceptHandler,
  type NetworkInterceptParams,
  type NetworkFulfillParams,
  type AbortReason,
  type NetworkAbortParams,
  type NetworkContinueParams,
  // Emulation methods
  EmulateSetViewportParamsSchema,
  EmulateSetUserAgentParamsSchema,
  EmulateSetGeolocationParamsSchema,
  EmulateSetOfflineParamsSchema,
  type EmulateSetViewportParams,
  type EmulateSetUserAgentParams,
  type EmulateSetGeolocationParams,
  type EmulateSetOfflineParams,
  // Dialog methods
  DialogActionSchema,
  DialogHandleParamsSchema,
  type DialogAction,
  type DialogHandleParams,
  // Trace methods
  TraceStartParamsSchema,
  TraceStopResultSchema,
  type TraceStartParams,
  type TraceStopResult,
  // Event subscription
  EventsSubscribeParamsSchema,
  type EventsSubscribeParams,
  // Context methods (Multi-Context Support)
  ContextOptionsSchema,
  ContextCreateParamsSchema,
  ContextCreateResultSchema,
  ContextInfoSchema,
  ContextListResultSchema,
  ContextDestroyParamsSchema,
  ContextDestroyResultSchema,
  type ContextOptions,
  type ContextCreateParams,
  type ContextCreateResult,
  type ContextInfo,
  type ContextListResult,
  type ContextDestroyParams,
  type ContextDestroyResult,
  // Frame methods (Frame & Shadow DOM Support)
  FrameInfoSchema,
  FrameListParamsSchema,
  FrameListResultSchema,
  FrameSwitchParamsSchema,
  FrameSwitchResultSchema,
  FrameMainParamsSchema,
  FrameMainResultSchema,
  type FrameInfo,
  type FrameListParams,
  type FrameListResult,
  type FrameSwitchParams,
  type FrameSwitchResult,
  type FrameMainParams,
  type FrameMainResult,
  // Streaming methods (Streaming Responses)
  StreamChunkParamsSchema,
  StreamEndParamsSchema,
  StreamErrorParamsSchema,
  StreamCancelParamsSchema,
  StreamCancelResultSchema,
  StreamStartResultSchema,
  type StreamChunkParams,
  type StreamEndParams,
  type StreamErrorParams,
  type StreamCancelParams,
  type StreamCancelResult,
  type StreamStartResult,
  // Approval methods (Human-in-the-Loop)
  ApprovalRuleMatchSchema,
  ApprovalRuleSchema,
  ApprovalConfigSchema,
  ApprovalElementInfoSchema,
  ApprovalRequiredParamsSchema,
  ApprovalDecisionSchema,
  ApprovalRespondParamsSchema,
  ApprovalRespondResultSchema,
  type ApprovalRuleMatch,
  type ApprovalRule,
  type ApprovalConfig,
  type ApprovalElementInfo,
  type ApprovalRequiredParams,
  type ApprovalDecision,
  type ApprovalRespondParams,
  type ApprovalRespondResult,
  // Method names
  BAPMethodSchema,
  type BAPMethod,
} from "./methods.js";

// Event types
export {
  // Page events
  PageEventTypeSchema,
  PageEventSchema,
  type PageEventType,
  type PageEvent,
  // Console events
  ConsoleLevelSchema,
  ConsoleEventSchema,
  type ConsoleLevel,
  type ConsoleEvent,
  // Network events
  RequestTimingSchema,
  NetworkRequestEventSchema,
  NetworkResponseEventSchema,
  NetworkFailedEventSchema,
  NetworkEventSchema,
  type RequestTiming,
  type NetworkRequestEvent,
  type NetworkResponseEvent,
  type NetworkFailedEvent,
  type NetworkEvent,
  // Dialog events
  DialogTypeSchema,
  DialogEventSchema,
  type DialogType,
  type DialogEvent,
  // Download events
  DownloadStateSchema,
  DownloadEventSchema,
  type DownloadState,
  type DownloadEvent,
  // Event type
  EventTypeSchema,
  type EventType,
  type BAPEvent,
} from "./events.js";

// Capability types
export {
  // Client capabilities
  ClientCapabilitiesSchema,
  type ClientCapabilities,
  // Server capabilities
  ServerFeaturesSchema,
  ServerLimitsSchema,
  ServerCapabilitiesSchema,
  type ServerFeatures,
  type ServerLimits,
  type ServerCapabilities,
  // Info types
  ClientInfoSchema,
  ServerInfoSchema,
  type ClientInfo,
  type ServerInfo,
  // Initialize
  InitializeParamsSchema,
  InitializeResultSchema,
  type InitializeParams,
  type InitializeResult,
  // Shutdown
  ShutdownParamsSchema,
  type ShutdownParams,
} from "./capabilities.js";

// Agent types (composite actions, observations, and data extraction)
export {
  // Condition types
  StepConditionStateSchema,
  StepConditionSchema,
  StepErrorHandlingSchema,
  type StepConditionState,
  type StepCondition,
  type StepErrorHandling,
  // Execution step types
  ExecutionStepSchema,
  type ExecutionStep,
  // Act params and result
  AgentActParamsSchema,
  StepErrorSchema,
  StepResultSchema,
  AgentActResultSchema,
  type AgentActParams,
  type StepError,
  type StepResult,
  type AgentActResult,
  // Observe types
  ActionHintSchema,
  ElementBoundsSchema,
  InteractiveElementSchema,
  type ActionHint,
  type ElementBounds,
  type InteractiveElement,
  // Element identity types (stable refs)
  ElementIdentitySchema,
  RefStabilitySchema,
  type ElementIdentity,
  type RefStability,
  // Annotation types (Set-of-Marks)
  AnnotationBadgeStyleSchema,
  AnnotationBoxStyleSchema,
  AnnotationStyleSchema,
  AnnotationLabelFormatSchema,
  AnnotationOptionsSchema,
  AnnotationMappingSchema,
  type AnnotationBadgeStyle,
  type AnnotationBoxStyle,
  type AnnotationStyle,
  type AnnotationLabelFormat,
  type AnnotationOptions,
  type AnnotationMapping,
  // Observe params and result
  AgentObserveParamsSchema,
  ObserveMetadataSchema,
  ObserveScreenshotSchema,
  AgentObserveResultSchema,
  type AgentObserveParams,
  type ObserveMetadata,
  type ObserveScreenshot,
  type AgentObserveResult,
  // Allowed actions
  ALLOWED_ACT_ACTIONS,
  type AllowedActAction,
  // Extract types
  ExtractionSchemaSchema,
  ExtractionModeSchema,
  AgentExtractParamsSchema,
  ExtractionSourceRefSchema,
  AgentExtractResultSchema,
  type ExtractionSchema,
  type ExtractionMode,
  type AgentExtractParams,
  type ExtractionSourceRef,
  type AgentExtractResult,
} from "./agent.js";
